controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.15
    wheel_radius: 0.035

    cmd_vel_timeout: 30.0

    enable_odom_tf: false
    use_stamped_vel: false